# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rachel Lin
email: rachellin@berkeley.edu
logo: logo.svg
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "http://rachellin.me" # the base hostname & protocol for your site
twitter_username: rchlelle
github_username:  rachelelle

social:
  - title: twitter
    url: http://twitter.com/rchlelle
  - title: facebook
    url: http://facebook.com/lin.rachel
  - title: linkedin
    url: http://linkedin.com/pub/rachel-lin/33/881/803/
  - title: behance
    url: http://behance.net/rachelelle
  - title: github
    url: http://github.com/rachelelle

# Build settings
markdown: kramdown
permalink: /:categories/:title/
